
root := ../..
targets := ${root}/lib/libsword.a
clean-targets := none
include ${root}/Makefile.cfg

cpp += swkey.cpp
cpp += listkey.cpp
cpp += versekey.cpp
cpp += strkey.cpp
cpp += treekey.cpp
cpp += treekeyidx.cpp

include ${root}/Makefile.post
