sudo: required
# Required for C++17 and modern CMake
dist: trusty
language: generic
before_install:
  - curl -sSL https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz | sudo tar -xzC /opt
  - curl -sSL https://cmake.org/files/v3.14/cmake-3.14.3-Linux-x86_64.tar.gz | sudo tar -xzC /opt
script: ./travis.sh || exit 1
matrix:
  include:
    - env: CXX=g++-8 CC=gcc-8
      addons: &gcc8addons
        apt:
          sources: &gccSources
            - ubuntu-toolchain-r-test
          packages:
            - &baseDeps [libbz2-dev, xz-utils, liblzma-dev, libcurl4-openssl-dev, zlib1g-dev, curl, libicu-dev]
            - [gcc-8, g++-8]
    - env: CXX=g++-8 CC=gcc-8 CMAKE_VERSION=3.8.0
      addons: *gcc8addons
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          sources: *gccSources
          packages: [*baseDeps, gcc-7, g++-7]
    - env: CXX=clang++-8.0 CC=clang-8.0
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-8.0
          packages: [*baseDeps, clang++-8.0]
notifications:
  irc: "chat.freenode.net#sword++"
