sudo: required
dist: bionic
language: generic
cache:
  directories:
  - /opt
before_install: ./travis-ci/before_install.sh
script: ./travis-ci/script.sh
matrix:
  include:
    - env: CXX=g++-9 CC=gcc-9 CMAKE_VERSION=3.14.0
      addons: &gcc9addons
        apt:
          sources: &gccSources
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - &baseDeps [libbz2-dev, xz-utils, liblzma-dev, libcurl4-openssl-dev, zlib1g-dev, curl, libicu-dev]
            - [gcc-9, g++-9]
    - env: CXX=g++-9 CC=gcc-9 CMAKE_VERSION=3.15.3
      addons: *gcc9addons
    - env: CXX=g++-8 CC=gcc-8 CMAKE_VERSION=3.15.3
      addons:
        apt:
          sources: *gccSources
          packages: [*baseDeps, gcc-8, g++-8]
    - env: CXX=g++-7 CC=gcc-7 CMAKE_VERSION=3.15.3
      addons:
        apt:
          packages: *baseDeps
    - env: CXX=clang++-8 CC=clang-8 CMAKE_VERSION=3.15.3
      addons: &clang8Addons
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages: [*baseDeps, clang-8]
    - env: CXX=clang++-9 CC=clang-9 CMAKE_VERSION=3.15.3
      addons: &clang9Addons
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages: [*baseDeps, clang-9]
notifications:
  irc: "chat.freenode.net#sword++"
