sudo: required
# Required for C++11/14 and modern cmake
dist: trusty
language: generic
before_install:
  - curl -sSL https://cmake.org/files/v3.7/cmake-3.7.0-Linux-x86_64.tar.gz | sudo tar -xzC /opt
  - curl -sSL https://cmake.org/files/v3.9/cmake-3.9.3-Linux-x86_64.tar.gz | sudo tar -xzC /opt
script: ./travis.sh || exit 1
matrix:
  include:
    - env: CXX=g++-7 CC=gcc-7
      addons: &gcc7addons
        apt:
          sources: &toolchainSources
            - ubuntu-toolchain-r-test
          packages:
            - &baseDeps [libbz2-dev, xz-utils, liblzma-dev, libcurl4-openssl-dev, zlib1g-dev, curl, libicu-dev]
            - [gcc-7, g++-7]
    - env: CXX=g++-7 CC=gcc-7 CMAKE_VERSION=3.7.0
      addons: *gcc7addons
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          sources: *toolchainSources
          packages: [*baseDeps, gcc-6, g++-6]
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources: *toolchainSources
          packages: [*baseDeps, gcc-5, g++-5]
    - env: CXX=clang++ CC=clang
      addons: *gcc7addons
notifications:
  irc: "chat.freenode.net#sword++"
