sudo: required
# Required for C++11/14 and modern cmake
dist: trusty
language: generic
before_install:
  - curl -sSL https://cmake.org/files/v3.3/cmake-3.3.0-Linux-x86_64.tar.gz | sudo tar -xzC /opt
  - curl -sSL https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz | sudo tar -xzC /opt
script: ./travis.sh || exit 1
matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5 CMAKE_VERSION=3.3.0
      addons:
        apt:
          sources: &toolchainSources
            - ubuntu-toolchain-r-test
          packages: &gcc5deps
            - &baseDependencies [libbz2-dev, xz-utils, liblzma-dev, libcurl4-openssl-dev, zlib1g-dev, cmake, libclucene-dev, curl]
            - gcc-5
            - g++-5
    - env: CXX=g++-5 CC=gcc-5 CMAKE_VERSION=3.6.2
      addons:
        apt:
          sources: *toolchainSources
          packages: *gcc5deps
    - env: CXX=g++-6 CC=gcc-6 CMAKE_VERSION=3.6.2
      addons:
        apt:
          sources: *toolchainSources
          packages: [*baseDependencies, gcc-6, g++-6]
    - env: CXX=g++-7 CC=gcc-7 CMAKE_VERSION=3.6.2
      addons:
        apt:
          sources: *toolchainSources
          packages: &gcc7deps [*baseDependencies, gcc-7, g++-7]
    - env: CXX=clang++ CC=clang CMAKE_VERSION=3.3.0
      addons: { apt: { packages: *gcc7deps } }
    - env: CXX=clang++ CC=clang CMAKE_VERSION=3.6.2
      addons: { apt: { packages: *gcc7deps } }
notifications:
  irc: "chat.freenode.net#sword++"
