all: aclocal automake autoheader autoconf

aclocal:
	./apps/autotools/bin/aclocal --acdir=./apps/autotools/share/aclocal

automake:
	-./apps/autotools/bin/automake --libdir=./apps/autotools/share/automake

autoheader:
	./apps/autotools/bin/autoheader -A ./apps/autotools/share/autoconf

autoconf:
	./apps/autotools/bin/autoconf -A ./apps/autotools/share/autoconf
