/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crosswire_android_sword_SWMgr_ModInfo */

#ifndef _Included_org_crosswire_android_sword_SWMgr_ModInfo
#define _Included_org_crosswire_android_sword_SWMgr_ModInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
