/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_crosswire_android_sword_SWModule_SearchProgressReporter */

#ifndef _Included_org_crosswire_android_sword_SWModule_SearchProgressReporter
#define _Included_org_crosswire_android_sword_SWModule_SearchProgressReporter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
