
root := ../..
subdirs := texts comments lexdict common filters
pre-targets := 
targets := ${root}/lib/libsword.a
clean-targets := none
include ${root}/Makefile.cfg

cpp += swmodule.cpp

include ${root}/Makefile.post
