
root := ../../..
subdirs := 
pre-targets := 
targets := ${root}/lib/libsword.a
clean-targets := none
include ${root}/Makefile.cfg

cpp += gbfhtml.cpp
cpp += gbfplain.cpp
cpp += gbfrtf.cpp
cpp += plainhtml.cpp
cpp += rwphtml.cpp
cpp += rwprtf.cpp
cpp += cipherfil.cpp
cpp += rtfhtml.cpp

cpp += gbfstrongs.cpp
cpp += gbffootnotes.cpp


include ${root}/Makefile.post
