
root := ../../..
subdirs := 
pre-targets := 
targets := ${root}/lib/libsword.a
include ${root}/Makefile.cfg

cpp += gbfplain.cpp
cpp += gbfrtf.cpp
cpp += gbfstrongs.cpp
cpp += gbffootnotes.cpp
cpp += rwprtf.cpp

include ${root}/Makefile.post
