
root := ../..
pre-targets := 
targets := ${root}/lib/libsword.a
clean-targets := none
include ${root}/Makefile.cfg

cpp += Greek2Greek.cpp
cpp += utilstr.cpp
cpp += unixstr.cpp

c += regex.c
c += utilstr.c

include ${root}/Makefile.post
