root := ..
subdirs := 
pre-targets := 
bin := yes
targets := cipherraw ciphertest ciphertest2 lexdump mkfastmod mod2vpl vpl2mod
include ${root}/Makefile.cfg

ifneq ($(nodeps),yes)
-include $(d)
endif
