
root := ../../..
subdirs := rawtext rawgbf ztext
pre-targets := 
targets := ${root}/lib/libsword.a
clean-targets := none
include ${root}/Makefile.cfg

cpp += swtext.cpp

include ${root}/Makefile.post
