/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.14u-20020903-2331
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/*
  +----------------------------------------------------------------------+
  | PHP version 4.0                                                      |
  +----------------------------------------------------------------------+
  | Copyright (c) 1997, 1998, 1999, 2000, 2001 The PHP Group             |
  +----------------------------------------------------------------------+
  | This source file is subject to version 2.02 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available at through the world-wide-web at                           |
  | http://www.php.net/license/2_02.txt.                                 |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Authors:                                                             |
  |                                                                      |
  +----------------------------------------------------------------------+
 */


#ifndef PHP_SWORD_H
#define PHP_SWORD_H

extern zend_module_entry Sword_module_entry;
#define phpext_Sword_ptr &Sword_module_entry

#ifdef PHP_WIN32
# define PHP_SWORD_API __declspec(dllexport)
#else
# define PHP_SWORD_API
#endif

PHP_MINIT_FUNCTION(Sword);
PHP_MSHUTDOWN_FUNCTION(Sword);
PHP_RINIT_FUNCTION(Sword);
PHP_RSHUTDOWN_FUNCTION(Sword);
PHP_MINFO_FUNCTION(Sword);

ZEND_NAMED_FUNCTION(_wrap_new_SWConfig);
ZEND_NAMED_FUNCTION(_wrap_delete_SWConfig);
ZEND_NAMED_FUNCTION(_wrap_SWConfig_Load);
ZEND_NAMED_FUNCTION(_wrap_SWConfig_Save);
ZEND_NAMED_FUNCTION(_wrap_SWConfig_set);
ZEND_NAMED_FUNCTION(_wrap_SWConfig_get);
ZEND_NAMED_FUNCTION(_wrap_SWMgr_findConfig);
ZEND_NAMED_FUNCTION(_wrap_new_SWMgr);
ZEND_NAMED_FUNCTION(_wrap_delete_SWMgr);
ZEND_NAMED_FUNCTION(_wrap_SWMgr_Load);
ZEND_NAMED_FUNCTION(_wrap_SWMgr_setGlobalOption);
ZEND_NAMED_FUNCTION(_wrap_SWMgr_getGlobalOption);
ZEND_NAMED_FUNCTION(_wrap_SWMgr_getGlobalOptionTip);
ZEND_NAMED_FUNCTION(_wrap_SWMgr_getGlobalOptions);
ZEND_NAMED_FUNCTION(_wrap_SWMgr_getGlobalOptionValues);
ZEND_NAMED_FUNCTION(_wrap_SWMgr_setCipherKey);
ZEND_NAMED_FUNCTION(_wrap_SWMgr_module);
ZEND_NAMED_FUNCTION(_wrap_new_SWModule);
ZEND_NAMED_FUNCTION(_wrap_SWModule_Error);
ZEND_NAMED_FUNCTION(_wrap_SWModule_isUnicode);
ZEND_NAMED_FUNCTION(_wrap_SWModule_getConfig);
ZEND_NAMED_FUNCTION(_wrap_SWModule_getConfigEntry);
ZEND_NAMED_FUNCTION(_wrap_SWModule_SetKey);
ZEND_NAMED_FUNCTION(_wrap_SWModule_Key);
ZEND_NAMED_FUNCTION(_wrap_SWModule_CreateKey);
ZEND_NAMED_FUNCTION(_wrap_SWModule_KeyText);
ZEND_NAMED_FUNCTION(_wrap_SWModule_Display);
ZEND_NAMED_FUNCTION(_wrap_SWModule_nullPercent);
ZEND_NAMED_FUNCTION(_wrap_SWModule_Search);
ZEND_NAMED_FUNCTION(_wrap_SWModule_createSearchFramework);
ZEND_NAMED_FUNCTION(_wrap_SWModule_hasSearchFramework);
ZEND_NAMED_FUNCTION(_wrap_SWModule_isSearchOptimallySupported);
ZEND_NAMED_FUNCTION(_wrap_SWModule_next);
ZEND_NAMED_FUNCTION(_wrap_SWModule_prev);
ZEND_NAMED_FUNCTION(_wrap_SWModule_inc);
ZEND_NAMED_FUNCTION(_wrap_SWModule_dec);
ZEND_NAMED_FUNCTION(_wrap_SWModule_setPosition);
ZEND_NAMED_FUNCTION(_wrap_SWModule_top);
ZEND_NAMED_FUNCTION(_wrap_SWModule_bottom);
ZEND_NAMED_FUNCTION(_wrap_SWModule_text);
ZEND_NAMED_FUNCTION(_wrap_SWModule_StripText);
ZEND_NAMED_FUNCTION(_wrap_SWModule_getRawEntry);
ZEND_NAMED_FUNCTION(_wrap_SWModule_setSkipConsecutiveLinks);
ZEND_NAMED_FUNCTION(_wrap_SWModule_getSkipConsecutiveLinks);
ZEND_NAMED_FUNCTION(_wrap_SWModule_getEntryAttributes);
ZEND_NAMED_FUNCTION(_wrap_SWModule_processEntryAttributes);
ZEND_NAMED_FUNCTION(_wrap_SWModule_isProcessEntryAttributes);
ZEND_NAMED_FUNCTION(_wrap_SWModule_Name);
ZEND_NAMED_FUNCTION(_wrap_SWModule_Description);
ZEND_NAMED_FUNCTION(_wrap_SWModule_Type);
ZEND_NAMED_FUNCTION(_wrap_SWModule_Direction);
ZEND_NAMED_FUNCTION(_wrap_SWModule_Encoding);
ZEND_NAMED_FUNCTION(_wrap_SWModule_Markup);
ZEND_NAMED_FUNCTION(_wrap_SWModule_Lang);
ZEND_NAMED_FUNCTION(_wrap_SWModule_isWritable);
ZEND_NAMED_FUNCTION(_wrap_SWModule_createModule);
ZEND_NAMED_FUNCTION(_wrap_SWModule_setEntry);
ZEND_NAMED_FUNCTION(_wrap_SWModule_deleteEntry);
ZEND_NAMED_FUNCTION(_wrap_SWModule_write);
ZEND_NAMED_FUNCTION(_wrap_SWModule_writeLink);
ZEND_NAMED_FUNCTION(_wrap_delete_SWModule);
ZEND_NAMED_FUNCTION(_wrap_new_SW_POSITION);
ZEND_NAMED_FUNCTION(_wrap_delete_SW_POSITION);
ZEND_NAMED_FUNCTION(_wrap_new_SWKey);
ZEND_NAMED_FUNCTION(_wrap_SWKey_clone);
ZEND_NAMED_FUNCTION(_wrap_SWKey_Persist);
ZEND_NAMED_FUNCTION(_wrap_SWKey_setPersist);
ZEND_NAMED_FUNCTION(_wrap_SWKey_Error);
ZEND_NAMED_FUNCTION(_wrap_SWKey_setText);
ZEND_NAMED_FUNCTION(_wrap_SWKey_getText);
ZEND_NAMED_FUNCTION(_wrap_SWKey_getShortText);
ZEND_NAMED_FUNCTION(_wrap_SWKey_compare);
ZEND_NAMED_FUNCTION(_wrap_SWKey_equals);
ZEND_NAMED_FUNCTION(_wrap_SWKey_decrement);
ZEND_NAMED_FUNCTION(_wrap_SWKey_increment);
ZEND_NAMED_FUNCTION(_wrap_SWKey_Traversable);
ZEND_NAMED_FUNCTION(_wrap_SWKey_Index);
ZEND_NAMED_FUNCTION(_wrap_SWKey_next);
ZEND_NAMED_FUNCTION(_wrap_SWKey_prev);
ZEND_NAMED_FUNCTION(_wrap_SWKey_setKey);
ZEND_NAMED_FUNCTION(_wrap_delete_SWKey);
ZEND_NAMED_FUNCTION(_wrap_new_VerseKey);
ZEND_NAMED_FUNCTION(_wrap_delete_VerseKey);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_clone);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_LowerBound);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_UpperBound);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_ClearBounds);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_decrement);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_increment);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_Traversable);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_getBookName);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_getBookAbbrev);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_Testament);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_Book);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_Chapter);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_Verse);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_Normalize);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_AutoNormalize);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_Headings);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_getOSISRef);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_compare);
ZEND_NAMED_FUNCTION(_wrap_VerseKey__compare);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_setLocale);
ZEND_NAMED_FUNCTION(_wrap_VerseKey_getLocale);
ZEND_NAMED_FUNCTION(_wrap_new_ListKey);
ZEND_NAMED_FUNCTION(_wrap_copy_ListKey);
ZEND_NAMED_FUNCTION(_wrap_delete_ListKey);
ZEND_NAMED_FUNCTION(_wrap_ListKey_clone);
ZEND_NAMED_FUNCTION(_wrap_ListKey_ClearList);
ZEND_NAMED_FUNCTION(_wrap_ListKey_Count);
ZEND_NAMED_FUNCTION(_wrap_ListKey_Remove);
ZEND_NAMED_FUNCTION(_wrap_ListKey_SetToElement);
ZEND_NAMED_FUNCTION(_wrap_ListKey_GetElement);
ZEND_NAMED_FUNCTION(_wrap_ListKey_add);
ZEND_NAMED_FUNCTION(_wrap_ListKey_copyFrom);
ZEND_NAMED_FUNCTION(_wrap_ListKey_setPosition);
ZEND_NAMED_FUNCTION(_wrap_ListKey_decrement);
ZEND_NAMED_FUNCTION(_wrap_ListKey_increment);
ZEND_NAMED_FUNCTION(_wrap_ListKey_Traversable);
ZEND_NAMED_FUNCTION(_wrap_ListKey_Index);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_getLocalName);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_setLocalName);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_getUserData);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_setUserData);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_getFullName);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_root);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_parent);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_firstChild);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_nextSibling);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_previousSibling);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_hasChildren);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_append);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_appendChild);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_insertBefore);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_remove);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_setOffset);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_getOffset);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_setPosition);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_Traversable);
ZEND_NAMED_FUNCTION(_wrap_TreeKey_Index);
ZEND_NAMED_FUNCTION(_wrap_new_LocaleMgr);
ZEND_NAMED_FUNCTION(_wrap_delete_LocaleMgr);
ZEND_NAMED_FUNCTION(_wrap_LocaleMgr_getLocale);
ZEND_NAMED_FUNCTION(_wrap_LocaleMgr_getAvailableLocales);
ZEND_NAMED_FUNCTION(_wrap_LocaleMgr_getDefaultLocaleName);
ZEND_NAMED_FUNCTION(_wrap_LocaleMgr_setDefaultLocaleName);
ZEND_NAMED_FUNCTION(_wrap_LocaleMgr_systemLocaleMgr);
ZEND_NAMED_FUNCTION(_wrap_new_SWText);
ZEND_NAMED_FUNCTION(_wrap_delete_SWText);
ZEND_NAMED_FUNCTION(_wrap_new_RawText);
ZEND_NAMED_FUNCTION(_wrap_RawText_createModule);
ZEND_NAMED_FUNCTION(_wrap_delete_RawText);
ZEND_NAMED_FUNCTION(_wrap_new_zText);
ZEND_NAMED_FUNCTION(_wrap_delete_zText);
ZEND_NAMED_FUNCTION(_wrap_zText_createModule);
ZEND_NAMED_FUNCTION(_wrap_new_RawGenBook);
ZEND_NAMED_FUNCTION(_wrap_delete_RawGenBook);
ZEND_NAMED_FUNCTION(_wrap_RawGenBook_createModule);
ZEND_NAMED_FUNCTION(_wrap_new_SWLD);
ZEND_NAMED_FUNCTION(_wrap_delete_SWLD);
ZEND_NAMED_FUNCTION(_wrap_new_RawLD);
ZEND_NAMED_FUNCTION(_wrap_delete_RawLD);
ZEND_NAMED_FUNCTION(_wrap_RawLD_createModule);
ZEND_NAMED_FUNCTION(_wrap_new_RawLD4);
ZEND_NAMED_FUNCTION(_wrap_delete_RawLD4);
ZEND_NAMED_FUNCTION(_wrap_RawLD4_createModule);
ZEND_NAMED_FUNCTION(_wrap_new_zLD);
ZEND_NAMED_FUNCTION(_wrap_delete_zLD);
ZEND_NAMED_FUNCTION(_wrap_zLD_createModule);
ZEND_NAMED_FUNCTION(_wrap_new_SWCompress);
ZEND_NAMED_FUNCTION(_wrap_delete_SWCompress);
ZEND_NAMED_FUNCTION(_wrap_SWCompress_Buf);
ZEND_NAMED_FUNCTION(_wrap_SWCompress_zBuf);
ZEND_NAMED_FUNCTION(_wrap_SWCompress_GetChars);
ZEND_NAMED_FUNCTION(_wrap_SWCompress_SendChars);
ZEND_NAMED_FUNCTION(_wrap_SWCompress_Encode);
ZEND_NAMED_FUNCTION(_wrap_SWCompress_Decode);
ZEND_NAMED_FUNCTION(_wrap_new_LZSSCompress);
ZEND_NAMED_FUNCTION(_wrap_delete_LZSSCompress);
ZEND_NAMED_FUNCTION(_wrap_LZSSCompress_Encode);
ZEND_NAMED_FUNCTION(_wrap_LZSSCompress_Decode);
ZEND_NAMED_FUNCTION(_wrap_new_ZipCompress);
ZEND_NAMED_FUNCTION(_wrap_delete_ZipCompress);
ZEND_NAMED_FUNCTION(_wrap_ZipCompress_Encode);
ZEND_NAMED_FUNCTION(_wrap_ZipCompress_Decode);
/*If you declare any globals in php_Sword.h uncomment this:
ZEND_BEGIN_MODULE_GLOBALS(Sword)
ZEND_END_MODULE_GLOBALS(Sword)
*/
#ifdef ZTS
#define SWORD_D  zend_Sword_globals *Sword_globals
#define SWORD_DC  , SWORD_D
#define SWORD_C  Sword_globals
#define SWORD_CC  , SWORD_C
#define SWORD_SG(v)  (Sword_globals->v)
#define SWORD_FETCH()  zend_Sword_globals *Sword_globals = ts_resource(Sword_globals_id)
#else
#define SWORD_D
#define SWORD_DC
#define SWORD_C
#define SWORD_CC
#define SWORD_SG(v)  (Sword_globals.v)
#define SWORD_FETCH()
#endif

#endif /* PHP_SWORD_H */
