<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.14u-20020903-2331
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

global $SWORD_LOADED__;
if ($SWORD_LOADED__) return;
$SWORD_LOADED__ = true;

/* if our extension has not been loaded, do what we can */
if (!extension_loaded("php_Sword")) {
	if (!dl("php_Sword.so")) return;
}



?>
