
root := ../../..
subdirs := rawcom rawfiles zcom hrefcom
pre-targets := 
targets := ${root}/lib/libsword.a
clean-targets := none
include ${root}/Makefile.cfg

cpp += swcom.cpp

include ${root}/Makefile.post
