######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 4 22:01:07 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += link_pkgconfig
PKGCONFIG += sword

# Input
SOURCES += qtLookup.cpp
