
root := ../..
subdirs := windoze X11
pre-targets := 
targets := ${root}/lib/libsword.a
clean-targets := none
include ${root}/Makefile.cfg

cpp += swdisp.cpp
cpp += swlog.cpp

include ${root}/Makefile.post
