
root := ../..
targets := ${root}/lib/libsword.a
clean-targets := none
include ${root}/Makefile.cfg

cpp += swconfig.cpp
cpp += swmgr.cpp
cpp += filemgr.cpp
cpp += swlocale.cpp

include ${root}/Makefile.post
