#!/bin/sh
(cd ..;./autogen.sh)
REV=`cd ..;basename \`pwd ..\`|cut -d\- -f2`
SWORDVER=`grep "define VERSI" ../include/config.h |cut -f2 -d"\""`

if test `echo $REV` == `echo $SWORDVER`; then 
	chmod +x *
	cd ..; ./autogen.sh
	cd ..; tar -v -c -p -s -z --exclude sword-$REV/bin -X sword-$REV/distignore -f sword-$REV.tar.gz sword-$REV/*
else
	echo $"Directory version is $REV, but config.h has $SWORDVER"
	exit 1

fi
