#!/bin/sh
REV=`cd ..;basename \`pwd ..\`|cut -d\- -f2`
SWORDVER=`grep "define SWORDVER" ../include/swversion.h |cut -f2 -d"\""`

if test `echo $REV` == `echo $SWORDVER`; then 
	chmod +x *
	chmod +x ../apps/X11/cheatah/configure
	chmod +x ../apps/X11/cheatah/missing
	#cp sapphire.cpp ../src/modules/common
	cd ../..; tar -v -c -p -s -z --exclude sword-$REV/bin -X sword-$REV/modlist -f sword-$REV.tar.gz sword-$REV/*
else
	echo $"Directory version is $REV, but swversion.h has $SWORDVER"
	exit 1

fi
