/* Header for module GBF, generated by p2c */
#ifndef GBF_H
#define GBF_H
/* p2c: Gbf.pas, line 5: Warning: Could not find module SYSUTILS [271] */


#include "sysutils.h"
/* p2c: Gbf.pas, line 5: Warning: Could not find module DIALOGS [271] */
#include "dialogs.h"


#ifdef GBF_G
# define vextern
#else
# define vextern extern
#endif



typedef enum {
  tokNull, tokEOF, tokHeader, tokContent, tokTail, tokStyle, tokWord,
  tokSpace, tokSync, tokControl, tokChar, tokFont
} TToken;
typedef enum {
  caBold, caSmallCaps, caItalic, caOTQuote, caRed, caSuperscript, caUnderline,
  caSubscript
} TCharacterAttribute;
typedef long TCharAttribs;



typedef struct TBookNameRec {
  Char Name[256], Abbr[256];
  uchar Num;
} TBookNameRec;

typedef TBookNameRec TBookAbbr[116];
/* p2c: Gbf.pas, line 25: 
 * Warning: Expected an expression, found a '/' [227] */
/* p2c: Gbf.pas, line 25: 
 * Warning: Expected an expression, found a '/' [227] */
/* p2c: Gbf.pas, line 25: Warning: Division by zero [163] */
/* p2c: Gbf.pas, line 26: Warning: Division by zero [163] */
/* p2c: Gbf.pas, line 26: Warning: Expected a ')', found a '(' [227] */
/* p2c: Gbf.pas, line 144: 
 * Warning: Expected an expression, found a '/' [227] */
/* p2c: Gbf.pas, line 144: 
 * Warning: Expected an expression, found a '/' [227] */
/* p2c: Gbf.pas, line 144: Warning: Division by zero [163] */
/* p2c: Gbf.pas, line 144: Warning: Division by zero [163] */
/* p2c: Gbf.pas, line 145: Warning: Mixing non-strings with strings [170] */
/* p2c: Gbf.pas, line 145: 
 * Warning: Expected a ')', found a string literal [227] */


extern TBookAbbr BookAbbr;

extern Char BookFileName[91][256];

vextern Char STR1[256];


#undef vextern

#endif /*GBF_H*/

/* End. */
