#####################################################################
# First, install the library itself
#

# Install the library
IF(BUILDING_SHARED)
    INSTALL(TARGETS sword
        RUNTIME DESTINATION "${BINDIR}"
        LIBRARY DESTINATION "${LIB_INSTALL_DIR}"
        ARCHIVE DESTINATION "${LIB_INSTALL_DIR}")
ENDIF(BUILDING_SHARED)
IF(BUILDING_STATIC)
    INSTALL(TARGETS sword_static
        RUNTIME DESTINATION "${BINDIR}"
        LIBRARY DESTINATION "${LIB_INSTALL_DIR}"
        ARCHIVE DESTINATION "${LIB_INSTALL_DIR}")
ENDIF(BUILDING_STATIC)
# Install the locales
INSTALL(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/locales.d
    DESTINATION "${SHARE_INSTALL_PREFIX}/sword")

# Install the headers
INSTALL(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/src/"
        DESTINATION "${INCLUDE_INSTALL_DIR}"
        FILES_MATCHING PATTERN "*.h")

# Install sysconf file
INSTALL(FILES "${CMAKE_CURRENT_BINARY_DIR}/sword.conf"
    DESTINATION "${SYSCONF_INSTALL_DIR}")
# Create the mods.d
INSTALL(DIRECTORY DESTINATION "${SHARE_INSTALL_PREFIX}/sword/mods.d")

MESSAGE(STATUS "Destination: ${CMAKE_INSTALL_PREFIX}")

SET(VERSION        ${SWORD_VERSION})
SET(CURL_LIBS    ${CURL_LIBRARY})
IF(WITH_CLUCENE)
    SET(CLUCENE_LIBS    ${CLUCENE_LIBRARY})
ENDIF(WITH_CLUCENE)
IF(WITH_ICU)
    SET(ICU_LIBS    "${ICU_LIBRARIES} ${ICU_I18N_LIBRARIES}")
ENDIF(WITH_ICU)

IF(LIBSWORD_LIBRARY_TYPE STREQUAL "Static")
    SET(SHAREDLIB_TRUE "#")
ELSE(LIBSWORD_LIBRARY_TYPE STREQUAL "Static")
    SET(SHAREDLIB_FALSE "#")
ENDIF(LIBSWORD_LIBRARY_TYPE STREQUAL "Static")

SET(prefix ${CMAKE_INSTALL_PREFIX})
SET(libdir ${LIB_INSTALL_DIR})
SET(exec_prefix ${BINDIR})
SET(includedir ${INCLUDE_INSTALL_DIR})
CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/sword.pc.in ${CMAKE_CURRENT_BINARY_DIR}/sword.pc @ONLY)
CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/src/swordxx/version.h.in ${CMAKE_CURRENT_BINARY_DIR}/include/version.h @ONLY)

INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/sword.pc
    DESTINATION "${LIB_INSTALL_DIR}/pkgconfig")
