
root := ../../..
subdirs := 
pre-targets := 
targets := ${root}/lib/libsword.a
clean-targets := none
include ${root}/Makefile.cfg

cpp += swinputmeth.cpp
cpp += nullim.cpp
cpp += hebrewmcim.cpp

include ${root}/Makefile.post
